import type { RouteDefinition } from "./types";

export const publicationRouteDefinitions: RouteDefinition[] = [
  { path: "/api/v1/teacher/publications", method: "get", operationId: "listTeacherPublications", tags: ["Publications", "Teacher"], summary: "Teacher publication list", responseSchema: "PublicationListResponse" },
  { path: "/api/v1/teacher/publications", method: "post", operationId: "createTeacherPublication", tags: ["Publications", "Teacher"], summary: "Create publication draft", requestBody: true, requestSchema: "CreatePublicationRequest", responseSchema: "PublicationActionResponse" },
  { path: "/api/v1/teacher/publications/{postId}", method: "get", operationId: "getTeacherPublication", tags: ["Publications", "Teacher"], summary: "Teacher publication detail", responseSchema: "PublicationDetailResponse" },
  { path: "/api/v1/teacher/publications/{postId}", method: "patch", operationId: "updateTeacherPublication", tags: ["Publications", "Teacher"], summary: "Update publication draft or schedule", requestBody: true, requestSchema: "UpdatePublicationRequest", responseSchema: "PublicationActionResponse" },
  { path: "/api/v1/teacher/publications/{postId}/publish", method: "post", operationId: "publishTeacherPublication", tags: ["Publications", "Teacher"], summary: "Publish a publication immediately", requestBody: true, requestSchema: "PublicationPublishRequest", responseSchema: "PublicationActionResponse" },
  { path: "/api/v1/teacher/publications/{postId}/schedule", method: "post", operationId: "scheduleTeacherPublication", tags: ["Publications", "Teacher"], summary: "Schedule a publication", requestBody: true, requestSchema: "PublicationScheduleRequest", responseSchema: "PublicationActionResponse" },
  { path: "/api/v1/teacher/publications/{postId}/cancel-schedule", method: "post", operationId: "cancelTeacherPublicationSchedule", tags: ["Publications", "Teacher"], summary: "Cancel a scheduled publication", responseSchema: "PublicationActionResponse" },
  { path: "/api/v1/teacher/publications/{postId}/retry", method: "post", operationId: "retryTeacherPublication", tags: ["Publications", "Teacher"], summary: "Retry a published or failed publication as a new revision", requestBody: true, requestSchema: "PublicationRetryRequest", responseSchema: "PublicationActionResponse" },
  { path: "/api/v1/teacher/publication-targets", method: "get", operationId: "listTeacherPublicationTargets", tags: ["Publications", "Teacher"], summary: "Teacher-visible publication targets", responseSchema: "PublicationTargetsResponse" },
  { path: "/api/v1/teacher/publication-targets/health", method: "get", operationId: "getPublicationProviderHealth", tags: ["Publications", "Teacher"], summary: "Publication provider health", responseSchema: "PublicationProviderHealthResponse" },
  { path: "/api/v1/owner/publication-targets", method: "get", operationId: "listOwnerPublicationTargets", tags: ["Publications", "Owner"], summary: "Owner publication targets", responseSchema: "PublicationTargetsResponse" },
  { path: "/api/v1/owner/publication-targets", method: "post", operationId: "createOwnerPublicationTarget", tags: ["Publications", "Owner"], summary: "Create a static publication target", requestBody: true, requestSchema: "CreatePublicationTargetRequest", responseSchema: "PublicationTargetMutationResponse" },
  { path: "/api/v1/owner/publication-targets/{targetId}", method: "patch", operationId: "updateOwnerPublicationTarget", tags: ["Publications", "Owner"], summary: "Update a static publication target", requestBody: true, requestSchema: "UpdatePublicationTargetRequest", responseSchema: "PublicationTargetMutationResponse" },
  { path: "/api/v1/internal/publications/process", method: "post", operationId: "processInternalPublications", tags: ["Internal", "Publications"], summary: "Process due publication deliveries", public: true, requestBody: true, requestSchema: "ProcessPublicationsRequest", responseSchema: "ProcessPublicationsResponse" }
];
